### PR TITLE
#81: add `JsonRpcResponseNormalizer::$debug`

### LINKED ISSUE #81: Inconsistent PHP exception procesing
At the present state this library processes "Internal Server Error" cases in the incorrect way.

## Security

First of all, it exposes the actual error message to the end user.
In case there is an exception thrown within JsonRpc method, like following:

```php
class Foo implements JsonRpcMethodInterface
{
    public function apply(array $paramList = null)
    {
        throw new \RuntimeException('Some exception message');
    }
}
```

the result output JSON looks like following:

```json
{"jsonrpc":"2.0","id":"test-641844ed220e9","error":{"code":-32603,"message":"Internal error","data":{"previous":"Some exception message"}}}
```

Actual exception message should never be exposed to the end API consumer, as it may contain vital information, and can be used for security exploit.

So the result JSON should look like following:

```json
{"jsonrpc":"2.0","id":"test-641844ed220e9","error":{"code":-32603,"message":"Internal error"}}
```

## Debug

There is a case, when exception information actually **should** be exposed to the end API consumer.
It should be so for project local development environment and for the unit testing.

The present implementation makes the mess for such case as well. It does not shows error stack trace, which make difficult to locate actual cause of the error.

Thus there should be a parameter, which can switch the exception rendering from "secure" (hide all) mode to "verbose" (show all) mode.

> Note: In most modern applications such condition is controlled via `APP_ENV` environment variable.

For the debug mode enabled the result error JSON should look like following:

```json
{
    "jsonrpc": "2.0",
    "id": "test-6418478c644f8",
    "error": {
        "code": -32603,
        "message": "Internal error",
        "data": {
            "code": 0,
            "message": "Some exception message",
            "trace": [
                {
                    "file": "/path/to/project/Foo.php",
                    "line": 64,
                    "function": "apply",
                    "class": "Foo",
                    "type": "->",
                    "args": [
                        {
                            "arg1": "foo",
                            "arg2": "bar",
                        }
                    ]
                },
                ...
            ]
        }
    }
}

```

## Original exception tracking loss

`ResponseCreator::createErrorResponse()` is implemented in the way the actual exception refernce is lost entirely.
To be more precise it is done at `JsonRpcInternalErrorException::__construct()`:

```php
public function __construct(\Exception $previousException = null)
    {
        parent::__construct(
            self::CODE,
            'Internal error',
            $previousException ? [self::DATA_PREVIOUS_KEY => $previousException->getMessage()] : []
        );
    }
```

Previous exception should be passed as a last argument during instantiating of the new exception. For example:

```php
try {
    // ...
} catch (\Exception $exception) {
    throw new MyLibraryException('My library has found an error', 123, $exception);
}
```

In such way the actual stack trace will be preserved and can be used for debugging.
And the original exception will be available via `Throwable::getPrevious()`.

While in present implementation the actual strack trace is lost along with the actual exception.

## Dev Notes

Most likely it should be fixed at `JsonRpcResponseNormalizer::normalizeError()`.

### PR DESCRIPTION
**Pull request by klimov-paul**
Add `JsonRpcResponseNormalizer::$debug` allowing rendering error trace if enabled trace if enabled.

Fixes #81

- Tests pass.
- BC seems to be kept. as only constructor signatures have been modified and only with optional arguments.

### CODE REVIEW

File: src/App/Serialization/JsonRpcResponseErrorNormalizer.php [hunk 1]
```diff
@@ -0,0 +1,151 @@
...
+     * @param array $trace raw exception stack trace.
+     * @return array simplified stack trace.
+     */
+    private function filterErrorTrace(array $trace): array
+    {
+        $trace = array_slice($trace, 0, $this->maxTraceSize);
+
+        $result = [];
+        foreach ($trace as $entry) {
+            if (!empty($entry['args'])) {
```
Comment (yoanm) [inline src/App/Serialization/JsonRpcResponseErrorNormalizer.php:83]:
```suggestion
            if (array_key_exists('args', $entry)) {
```
_Related test is red locally without that as `args` is there but empty_

Comment (klimov-paul) [reply src/App/Serialization/JsonRpcResponseErrorNormalizer.php]: Fixed.

File: composer.json [hunk 2]
```diff
@@ -39,6 +39,7 @@
     "behat/behat": "~3.0",
     "squizlabs/php_codesniffer": "3.*",
     "phpunit/phpunit": "^7.0 || ^8.0",
+    "phpspec/prophecy": "^1.0",
```
[the remark this answers is not in the document]
Comment (yoanm) [reply composer.json]: Indeed, most likely a miss due to another package requiring that one.
Fixed on master.

File: src/App/Serialization/JsonRpcResponseErrorNormalizer.php [hunk 3]
```diff
@@ -0,0 +1,151 @@
...
+        $this->simplifyTraceArguments = $simplifyTraceArguments;
+    }
+
+    /**
+     * @param JsonRpcExceptionInterface $error
+     * @return array
+     */
+    public function normalize(JsonRpcExceptionInterface $error) : array
+    {
+        return $this->composeDebugErrorData($error->getPrevious() ?? $error);
```
Comment (yoanm) [inline src/App/Serialization/JsonRpcResponseErrorNormalizer.php:50]: What's the purpose of skipping original error if there is a previous one ?

File: src/App/Serialization/JsonRpcResponseErrorNormalizer.php [hunk 4]
```diff
@@ -0,0 +1,151 @@
...
+                $args[$key] = '[' . $this->simplifyArguments($value) . ']';
+            } elseif ($value===null) {
+                $args[$key] = 'null';
+            } elseif (is_resource($value)) {
+                $args[$key] = 'resource';
+            }
+
+            if (is_string($key)) {
+                $args[$key] = "'" . $key . "' => " . $args[$key];
+            } elseif ($isAssoc) {
```
Comment (yoanm) [inline src/App/Serialization/JsonRpcResponseErrorNormalizer.php:144]: I don't understand that condition. Shouldn't be just a `else` ?

**Review by yoanm — COMMENTED** [review]
Two comments, else nice work 👌

File: src/App/Serialization/JsonRpcResponseErrorNormalizer.php (hunk 3 above)
Comment (klimov-paul) [reply src/App/Serialization/JsonRpcResponseErrorNormalizer.php:50]: Here we create a debug info about an exception occured.

`JsonRpcExceptionInterface` mainly serves as a wrapper around raw exception. See:
https://github.com/yoanm/php-jsonrpc-server-sdk/blob/v3.2.1/src/App/Creator/ResponseCreator.php#L54-L63

There is no point to display debug for `JsonRpcInternalErrorException` as it will always refer to the same line throwed, has the same class name and so on.

Thus `JsonRpcExceptionInterface` has a little value on its own ragarding debug info composition.
Using previous exception creates much cleaner and useful results.

File: src/App/Serialization/JsonRpcResponseErrorNormalizer.php (hunk 4 above)
Comment (klimov-paul) [reply src/App/Serialization/JsonRpcResponseErrorNormalizer.php]: Indeed.
Fixes.

Comment (klimov-paul) [reply src/App/Serialization/JsonRpcResponseErrorNormalizer.php:130]: Although, no - original condition is correct.
Reverted.

In this line we check if array contains both numeric keys and string keys or has keys reordered. If it does - we display the keys.
If array contains only numeric keys in assoc order we do not display keys at all, creating much cleaner output.

Comment (klimov-paul) [reply src/App/Serialization/JsonRpcResponseErrorNormalizer.php:130]: For list-type array:

```php
[
    'foo',
    'bar',
]
```

representation will be:

```
['foo', 'bar']
```

But for the following array:

```php
[
    9 => 'nine',
    5 => 'five'
]
```

representation will be:

```
[9 => 'nine', 5 => 'five']
```

For the array with mixed keys:

```php
[
    'foo',
    'name' => 'bar',
]
```

representation will be:

```
[0 => 'foo', 'name' => 'bar']
```

Comment (yoanm) [reply src/App/Serialization/JsonRpcResponseErrorNormalizer.php:130]: Got it 👍 Test params updated accordingly

**Comment by yoanm** [comment]
Humm, something wrong with the coverage, I do see it at 100% locally 🤔 
I'll try to figure out what happens
